# Ender chest spin rate in revolutions per minute.
rpm: 45.0

# Time in seconds to wait before the ender chest reappears.
secondsHidden: 60

# Type of particle to show when closing the ender chest.
# Check these lists for possible values:
#  路 For 1.12.x: https://papermc.io/javadocs/paper/1.12/org/bukkit/Particle.html
#  路 For 1.13.x: https://papermc.io/javadocs/paper/1.13/org/bukkit/Particle.html
#  路 For 1.14.x: https://papermc.io/javadocs/paper/1.14/org/bukkit/Particle.html
#  路 For 1.15.x: https://papermc.io/javadocs/paper/1.15/org/bukkit/Particle.html
particleType: END_ROD
# The number of particles to spawn.
particleCount: 100
# The amount of motion the particles will have.
particleSpeed: 0.1
