{
  "name": "FancyE-Chests",
  "authors": [
    "emilyy-dev"
  ],
  "version": "${pluginVersion}",
  "website": "https://github.com/emilyy-dev/FancyE-Chests",
  "main": "io.github.emilyydev.fancyechests.FancyEChestsPlugin",
  "load": "POSTWORLD",
  "softdepend": [
    "Vault"
  ]
}
