{
  "name": "FancyE-Chests",
  "authors": [
    "Fefo"
  ],
  "version": "${pluginVersion}",
  "main": "com.github.fefo.fancyechests.FancyEChestsPlugin",
  "load": "POSTWORLD",
  "softdepend": [
    "Vault"
  ]
}
